apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.fullname" . }}
  labels:
{{ include "app.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "app.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "app.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
        {{- range .Values.service.ports }}
            - name: {{ .name }}
              containerPort: {{ .port }}
              protocol: {{ .protocol | default "TCP" }}
        {{- end }}
        {{- if .Values.service.probe.enabled }}
          livenessProbe:
            {{- if eq .Values.service.probe.port "http" }}
            httpGet:
              path: /
            {{- else }}
            tcpSocket:
            {{- end }}
              port: {{ .Values.service.probe.port }}
          readinessProbe:
            {{- if eq .Values.service.probe.port "http" }}
            httpGet:
              path: /
            {{- else }}
            tcpSocket:
            {{- end }}
              port: {{ .Values.service.probe.port }}
        {{- end }}
          volumeMounts:
          {{- if .Values.persistence.enabled }}
            - name: data
              mountPath: {{ .Values.persistence.path }}
          {{- end }}
          {{- if .Values.persistence.extraVolumes }}
            {{- toYaml .Values.persistence.extraVolumeMounts | nindent 12 }}
          {{- end }}
          resources:
              {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
        affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
      - name: data
      {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.existingClaim | default (include "app.fullname" .) }}
      {{- end -}}
      {{- if .Values.persistence.extraVolumes }}
      {{- toYaml .Values.persistence.extraVolumes | nindent 6 }}
      {{- end }}
