pipeline {
    agent none
    triggers {
        pollSCM 'H/15 * * * *'
    }
    stages {
        stage("build") {
            agent any
            steps {
                dir("dists") {
                    git branch: 'develop', url: 'https://github.com/akudet/devops.git'
                }
                script {
                    def projs = ["."]
                    def pipeline = load "$WORKSPACE/dists/jenkins/pipeline.groovy"
                    pipeline.build(projs)
                }
            }
        }
    }
}
